name: Auto test whether the repo is working
run-name: ${{ github.actor }} is testing his/her repo 🚀

on: 
  pull_request:
    types: [opened]
  push:
    branches: [main]

jobs:
  Prepare-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update test yaml
        run: node renewFolder.js

      - name: ls
        run: ls {{github.workspace}}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update test yaml
          commit_options: '--no-verify'
          commit_user_name: ${{ github.actor }}
          commit_user_email: ${{ github.actor }}@users.noreply.github.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          directory: [demo, student-a, student-acopy, student-acopy2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test
      env:
        DIRECTORY: ${{ matrix.directory }}
      run: |
        cd $DIRECTORY
        docker compose up -d
        npm install
        npm run test
        docker compose down

