name: Auto test whether the repo is working
run-name: ${{ github.actor }} is testing his/her repo 🚀

on: 
  pull_request:
    types: [opened]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: ls
      run: ls

    - name: Build and test
      run: bash ./loop.sh